apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
type: Opaque
data:
  database_uri: cG9zdGdyZXErcHN5Y29wZzI6Ly9wb3N0Z3Jlc3Q6cG9zdGdyZXNAaG9zdDoxNTY3L3Bvc3RncmVz
  username: cG9zdGdyZXM=        # Base64 encoded value of "postgres"
  password: cG9zdGdyZXM=        # Base64 encoded value of "postgres"
  database: cG9zdGdyZXM=        # Base64 encoded value of "postgres"
  
