---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - description: The URL to the git repo
      name: GIT_REPO
      type: string
    - default: master
      description: The reference (branch or ref)
      name: GIT_REF
      type: string
    - default: petshop
      description: Name of the application
      name: APP_NAME
      type: string
    - default: "image-registry.openshift-image-registry.svc:5000/$ (context.pipelineRun.namespace)/$(params.APP NAME):latest"
      description: The name of the image to build
      name: IMAGE_NAME
      type: string
